### ISSUE TITLE
Dynamic index name resolution is broken in master branch

### ISSUE THREAD

**Issue by vovayartsev** [StephaneRob/algoliax#35]
### Environment

Elixir 1.8 / 1.9
Algoliax from latest master

### Steps to reproduce

Define an indexer:

```
defmodule MyIndexer do
  use Algoliax.Indexer,
    index_name: :generate_index_name,
    ...

  def generate_index_name do
    "environment-dependent-index-name"
  end
end
```

then call `MyIndexer.configure_index()`

### Expected behavior
Only one index created, with name "environment-dependent-index-name"

### Actual behavior
Two indexes created in Algolia:
* generate_index_name
* environment-dependent-index-name

I believe this happens because the actual index configuration happens before the `apply` call:
![image](https://user-images.githubusercontent.com/204231/90393527-fac82a80-e0a1-11ea-8f18-b2d1a6ecf88d.png)

**Comment by StephaneRob** [comment]
Thanks @vovayartsev! You're right i'm fixing it.

**Comment by StephaneRob** [comment]
@vovayartsev can you try #36? and let me know

**Comment by vovayartsev** [comment]
Tested and it works great! Thanks for such a quick turnaround. ✅ 


On a related note. Probably not a big issue, but when I started `iex -S mix` and executed `configure_index()` for the very first time, I noticed in the logs this line **twice**:
```
[debug] CONFIGURE_INDEX: PUT https://<project-id>.algolia.net/1/indexes/<index-name>/settings
```

The outcome is totally OK, as the payload in both PUT requests was the same.
So not really an issue for me - just wanted to share this finding.

**Comment by StephaneRob** [comment]
@vovayartsev 👍 

Actually the `configure_index/0` is necessary if the config changes at runtime (or hot upgrade). The log appears twice because we ensure that the index is configured before using it. So when you execute `configure_index/0` the index is automatically setup and then the actual `configure_index/0` is executed (both use same logic).
